spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dev.com:5432/test
    username: test
    password: test
    hikari:
      maximum-pool-size: 32
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20

logging:
  level:
   root: warn
#   org.hibernate: debug
#   org.hibernate.SQL: debug
#   org.hibernate.type: trace
#   org.hibernate.type.descriptor.sql: trace
